using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class ServerTab : Control
    {
        [Dependency] private IConfigurationManager _config = default!;
        [Dependency] private IClientConsoleHost _console = default!;

        public ServerTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _config.OnValueChanged(CCVars.OocEnabled, OocEnabledChanged, true);
            _config.OnValueChanged(CCVars.LoocEnabled, LoocEnabledChanged, true);

            ServerShutdownButton.OnPressed += _ => _console.ExecuteCommand("shutdown");

            AfkTime.OnTextEntered += args => SendFloatCVar(CCVars.AfkTime.Name, args.Text);
            AfkTime.OnFocusExit += args => SendFloatCVar(CCVars.AfkTime.Name, args.Text);
            AdminAfkTime.OnTextEntered += args => SendFloatCVar(CCVars.AdminAfkTime.Name, args.Text);
            AdminAfkTime.OnFocusExit += args => SendFloatCVar(CCVars.AdminAfkTime.Name, args.Text);
            AfkConfirmTimeout.OnTextEntered += args => SendFloatCVar(CCVars.AfkConfirmTimeout.Name, args.Text);
            AfkConfirmTimeout.OnFocusExit += args => SendFloatCVar(CCVars.AfkConfirmTimeout.Name, args.Text);
        }

        private void SendFloatCVar(string cvar, string text)
        {
            if (string.IsNullOrWhiteSpace(text) ||
                !float.TryParse(text, out var value) ||
                value < 0f)
            {
                return;
            }

            _console.ExecuteCommand($"changecvar {cvar} {value}");
        }

        private void OocEnabledChanged(bool value)
        {
            SetOocButton.Pressed = value;
        }

        private void LoocEnabledChanged(bool value)
        {
            SetLoocButton.Pressed = value;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _config.UnsubValueChanged(CCVars.OocEnabled, OocEnabledChanged);
                _config.UnsubValueChanged(CCVars.LoocEnabled, LoocEnabledChanged);
            }
        }
    }
}
